theme: jekyll-theme-minimal

title: Welcome to my blog about data, language, career and self-discovery as an NLP engineer 

description: Feel free to bookmark this to keep an eye on my project updates
